# Generated by Django 5.2.5 on 2025-08-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_date__isnull', True)), fields=('book', 'member'), name='unique_borrow'),
        ),
    ]
