# Generated by Django 5.2.5 on 2025-08-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='membeership_date',
            new_name='membership_date',
        ),
    ]
